errorbar(t, T, sigma_T, sigma_t,'x', label='Temperaturmessung')
plot(t[8:11], T[8:11])
optimizedParameters1, s = opt.curve_fit(linear, t[0:8], T[0:8])
plot(t[0:17], linear(t[0:17], *optimizedParameters1), label="fit1")
optimizedParameters2, s = opt.curve_fit(linear, t[10:], T[10:])
plot(t[4:], linear(t[4:], *optimizedParameters2), label="fit1")
t_zwickel = 248
plt.vlines(t_zwickel, min(T), max(T), label='vline')
xlabel('Zeit in s', fontsize=20)
ylabel('Temperatur in °C', fontsize=20)
legend(fontsize=13, loc='center left')
grid()
plt.tight_layout()
savefig('eis1')
show()